// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dygpekixmgbduxmwauku.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR5Z3Bla2l4bWdiZHV4bXdhdWt1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc0MDc1NjAsImV4cCI6MjA2Mjk4MzU2MH0.3LZyb7benNnFGDsgxIoeHgBT2Q3stipeCO5vEY3ra0A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);